version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Sample
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - ./data:/var/lib/mysql
