version: "3.8"

services:
  mysql_server:
    container_name: mysql_server
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_server/mysql_server.cnf:/etc/mysql/conf.d/mysql_server.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "irandb"
      MYSQL_USER: "springuser"
      MYSQL_PASSWORD: "1234"

  irandb_backend:
    container_name: irandb_backend
    build: ./irandb_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVE_PROFILE: staging
      MYSQL_HOST: mysql_server
    depends_on: 
      - mysql_server

#  mysql_admin:
#    container_name: mysql_admin
#    image: adminer
#    restart: always
#    ports:
#      - "9090:8080"
